/* ============================================================
   FACH-SPEZIFISCHE DEMO-FRAGEN
   Je 5 Fragen für alle 13 FMS-Fächer
   ============================================================ */

export interface DemoFrage {
  id: number;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  kategorie: string;
  schwierigkeit: "leicht" | "mittel" | "schwer";
}

export const FACH_FRAGEN: Record<string, DemoFrage[]> = {

  allgemein: [
    { id: 1, question: "Was versteht man unter 'Retrieval Practice' (aktives Abrufen)?", options: ["Mehrfaches Lesen des gleichen Textes", "Das aktive Erinnern von Informationen aus dem Gedächtnis ohne Hilfsmittel", "Das Erstellen von Zusammenfassungen mit KI", "Das Anschauen von Erklärvideos"], correct: 1, explanation: "Retrieval Practice bedeutet, Wissen aktiv aus dem Gedächtnis abzurufen – z.B. durch Selbsttests oder das Aufschreiben von Erlerntem ohne Vorlage. Studien zeigen, dass dies deutlich effektiver ist als erneutes Lesen.", kategorie: "Lernstrategien", schwierigkeit: "leicht" },
    { id: 2, question: "Welche drei Grundbedürfnisse müssen laut Selbstbestimmungstheorie erfüllt sein, damit Motivation entsteht?", options: ["Sicherheit, Erfolg, Anerkennung", "Autonomie, Kompetenz, Zugehörigkeit", "Interesse, Disziplin, Belohnung", "Planung, Durchführung, Reflexion"], correct: 1, explanation: "Die Selbstbestimmungstheorie (Deci & Ryan) nennt Autonomie, Kompetenz und Zugehörigkeit als die drei zentralen Grundbedürfnisse für intrinsische Motivation.", kategorie: "Motivationstheorie", schwierigkeit: "mittel" },
    { id: 3, question: "Was ist der Hauptvorteil von 'verteiltem Lernen' gegenüber 'Massen-Lernen' (Cramming)?", options: ["Verteiltes Lernen ist schneller", "Massen-Lernen ist für Prüfungen besser geeignet", "Verteiltes Lernen führt zu besserem Langzeitgedächtnis", "Beide Methoden sind gleich effektiv"], correct: 2, explanation: "Verteiltes Lernen (Spacing Effect) nutzt die natürliche Vergessenskurve: Wenn man kurz vor dem Vergessen wiederholt, wird die Erinnerungsspur stärker.", kategorie: "Lernstrategien", schwierigkeit: "leicht" },
    { id: 4, question: "Was beschreibt die 'Feynman-Methode' als Lernstrategie?", options: ["Lernen durch Karteikarten und Wiederholung", "Einen Stoff so einfach erklären, dass ihn ein Kind verstehen würde", "Lernen in kurzen Intervallen mit Pausen", "Zusammenfassungen mit KI erstellen"], correct: 1, explanation: "Die Feynman-Methode besagt: Wenn du ein Konzept wirklich verstehst, kannst du es einfach erklären. Wenn du es nicht einfach erklären kannst, hast du noch Lücken.", kategorie: "Lernstrategien", schwierigkeit: "leicht" },
    { id: 5, question: "Was versteht man unter 'Metakognition' im Lernkontext?", options: ["Das Lernen mit digitalen Medien", "Das Nachdenken über das eigene Denken und Lernen", "Das Erstellen von Mindmaps", "Das gemeinsame Lernen in der Gruppe"], correct: 1, explanation: "Metakognition bezeichnet die Fähigkeit, das eigene Denken und Lernen zu beobachten und zu steuern. Dazu gehören: Planung, Monitoring und Evaluation.", kategorie: "Lernkompetenz", schwierigkeit: "mittel" },
  ],

  deutsch: [
    { id: 1, question: "Was ist das Hauptmerkmal eines Erörterungsaufsatzes?", options: ["Erzählen einer Geschichte mit Spannungsbogen", "Beschreiben eines Gegenstands oder Vorgangs", "Argumentatives Abwägen von Pro und Contra zu einer Frage", "Zusammenfassen eines literarischen Textes"], correct: 2, explanation: "Eine Erörterung untersucht eine Frage oder These argumentativ: Sie stellt Argumente und Gegenargumente gegenüber und kommt zu einem begründeten Schluss.", kategorie: "Aufsatzformen", schwierigkeit: "leicht" },
    { id: 2, question: "Was versteht man unter einem 'Hypotaxe' in der Grammatik?", options: ["Ein einfacher Hauptsatz ohne Nebensatz", "Eine Satzstruktur mit über- und untergeordneten Sätzen (Nebensätze)", "Eine Aufzählung gleichrangiger Hauptsätze", "Ein Satz ohne Verb"], correct: 1, explanation: "Hypotaxe bezeichnet die Unterordnung von Nebensätzen unter einen Hauptsatz. Gegenteil: Parataxe (Aneinanderreihung gleichrangiger Hauptsätze).", kategorie: "Grammatik", schwierigkeit: "mittel" },
    { id: 3, question: "Welche Funktion hat ein Textbeleg (Zitat) in einer Textanalyse?", options: ["Er macht den Text länger", "Er ersetzt die eigene Argumentation", "Er belegt und stützt die eigene Interpretation mit Textstellen", "Er fasst den Inhalt zusammen"], correct: 2, explanation: "Textbelege (Zitate mit Zeilenangabe) sind unverzichtbar in der Textanalyse: Sie zeigen, dass Interpretationen am Text selbst nachgewiesen werden können.", kategorie: "Textanalyse", schwierigkeit: "leicht" },
    { id: 4, question: "Was ist eine 'Metapher' als rhetorisches Mittel?", options: ["Eine direkte Vergleich mit 'wie'", "Eine bildhafte Übertragung ohne Vergleichswort", "Eine Übertreibung zur Verstärkung", "Eine Wiederholung am Satzanfang"], correct: 1, explanation: "Eine Metapher überträgt Bedeutung ohne Vergleichswort (z.B. 'das Feuer der Leidenschaft'). Im Gegensatz dazu steht der Vergleich ('brennend wie Feuer').", kategorie: "Rhetorik & Stilmittel", schwierigkeit: "leicht" },
    { id: 5, question: "Was kennzeichnet den Erzählstandpunkt des 'auktorialen Erzählers'?", options: ["Er erzählt aus der Ich-Perspektive und erlebt alles selbst", "Er weiss alles über alle Figuren und kann kommentieren", "Er berichtet nur, was er von aussen sieht", "Er wechselt ständig die Perspektive"], correct: 1, explanation: "Der auktoriale Erzähler ist allwissend: Er kennt die Gedanken aller Figuren, kann zeitlich vor- und zurückspringen und kommentiert das Geschehen.", kategorie: "Literatur & Erzähltechnik", schwierigkeit: "mittel" },
  ],

  franzoesisch: [
    { id: 1, question: "Quelle est la règle principale du subjonctif présent?", options: ["On l'utilise après des verbes de certitude", "On l'utilise après des verbes d'opinion, de volonté, d'émotion ou de doute", "On l'utilise uniquement au passé", "On l'utilise seulement avec 'que'"], correct: 1, explanation: "Le subjonctif s'emploie après des verbes exprimant une volonté (vouloir que), une émotion (être content que), un doute (douter que) ou une nécessité (il faut que).", kategorie: "Grammaire", schwierigkeit: "mittel" },
    { id: 2, question: "Comment forme-t-on le passé composé avec l'auxiliaire 'être'?", options: ["Avec tous les verbes d'action", "Avec les verbes pronominaux et certains verbes de mouvement (aller, venir, partir...)", "Uniquement avec les verbes irréguliers", "Avec les verbes qui se terminent en -ir"], correct: 1, explanation: "On utilise 'être' comme auxiliaire avec les verbes pronominaux (se lever) et avec environ 17 verbes de mouvement ou d'état (aller, venir, partir, arriver, naître, mourir...).", kategorie: "Grammaire", schwierigkeit: "leicht" },
    { id: 3, question: "Qu'est-ce qu'une 'argumentation' dans un texte?", options: ["Un récit d'événements chronologiques", "Un ensemble de raisonnements pour défendre une thèse", "Une description détaillée d'un lieu", "Un dialogue entre deux personnages"], correct: 1, explanation: "L'argumentation vise à convaincre le lecteur en présentant des arguments (thèse, arguments, exemples, conclusion) pour défendre un point de vue.", kategorie: "Expression écrite", schwierigkeit: "leicht" },
    { id: 4, question: "Quelle est la différence entre l'imparfait et le passé composé?", options: ["Il n'y a pas de différence", "L'imparfait décrit des états ou actions habituelles, le passé composé des actions ponctuelles terminées", "L'imparfait est plus formel", "Le passé composé s'utilise uniquement à l'oral"], correct: 1, explanation: "L'imparfait exprime des actions habituelles, des descriptions ou des actions en cours dans le passé. Le passé composé exprime des actions ponctuelles, terminées ou dont on voit le résultat.", kategorie: "Grammaire", schwierigkeit: "mittel" },
    { id: 5, question: "Que signifie 'analyser un texte littéraire'?", options: ["Résumer l'histoire en quelques phrases", "Identifier le thème, la structure, les procédés stylistiques et l'intention de l'auteur", "Traduire le texte mot à mot", "Donner son opinion personnelle sans justification"], correct: 1, explanation: "Analyser un texte littéraire, c'est étudier sa forme (structure, style, figures de rhétorique) et son fond (thèmes, personnages, message) en citant des passages précis.", kategorie: "Compréhension de texte", schwierigkeit: "mittel" },
  ],

  englisch: [
    { id: 1, question: "What is the difference between 'since' and 'for' in the present perfect?", options: ["There is no difference", "'Since' refers to a point in time, 'for' refers to a duration", "'For' is only used in questions", "'Since' is more formal than 'for'"], correct: 1, explanation: "'Since' indicates the starting point of an action (since Monday, since 2020), while 'for' indicates the duration (for three days, for two years).", kategorie: "Grammar", schwierigkeit: "leicht" },
    { id: 2, question: "What is a 'thesis statement' in an essay?", options: ["The conclusion of the essay", "A sentence that summarises the main argument of the essay", "A list of all the points discussed", "The first sentence of the introduction"], correct: 1, explanation: "A thesis statement is a clear, concise sentence (usually at the end of the introduction) that states the main argument or claim of the essay. It guides the entire essay.", kategorie: "Writing", schwierigkeit: "leicht" },
    { id: 3, question: "What does 'implicit meaning' in a text refer to?", options: ["Information that is directly stated", "Meaning that is suggested or implied but not directly stated", "The title of the text", "The author's biography"], correct: 1, explanation: "Implicit meaning is what the author suggests without stating it directly. Readers must 'read between the lines' to understand the full message.", kategorie: "Text Analysis", schwierigkeit: "mittel" },
    { id: 4, question: "Which sentence uses the passive voice correctly?", options: ["The teacher explained the grammar.", "The grammar was explained by the teacher.", "The grammar explained the teacher.", "The teacher was explaining grammar."], correct: 1, explanation: "The passive voice is formed with 'to be' + past participle. It emphasises the action or the object rather than the subject performing the action.", kategorie: "Grammar", schwierigkeit: "leicht" },
    { id: 5, question: "What is the purpose of 'cohesive devices' in writing?", options: ["To make the text longer", "To connect ideas and ensure the text flows logically", "To introduce new vocabulary", "To summarise the main points"], correct: 1, explanation: "Cohesive devices (e.g. however, therefore, in addition, as a result) connect sentences and paragraphs, creating a logical flow and making the text easier to read.", kategorie: "Writing", schwierigkeit: "mittel" },
  ],

  mathematik: [
    { id: 1, question: "Was ist der Unterschied zwischen einer Gleichung und einer Ungleichung?", options: ["Es gibt keinen Unterschied", "Eine Gleichung hat ein '='-Zeichen, eine Ungleichung ein '<', '>' oder '≤/≥'-Zeichen", "Eine Ungleichung hat immer mehr Lösungen", "Gleichungen haben nur eine Lösung, Ungleichungen keine"], correct: 1, explanation: "Eine Gleichung sagt aus, dass zwei Ausdrücke gleich sind (a = b). Eine Ungleichung beschreibt eine Ordnungsbeziehung (a < b, a ≥ b) und hat oft unendlich viele Lösungen.", kategorie: "Algebra", schwierigkeit: "leicht" },
    { id: 2, question: "Was beschreibt die Ableitung f'(x) einer Funktion f(x)?", options: ["Den Flächeninhalt unter dem Graphen", "Die momentane Änderungsrate (Steigung) der Funktion an der Stelle x", "Den Maximalwert der Funktion", "Die Nullstellen der Funktion"], correct: 1, explanation: "Die Ableitung f'(x) gibt die momentane Änderungsrate der Funktion an – geometrisch entspricht sie der Steigung der Tangente an den Graphen bei x.", kategorie: "Analysis", schwierigkeit: "mittel" },
    { id: 3, question: "Wie lautet der Satz des Pythagoras?", options: ["a + b = c", "a² + b² = c²", "a × b = c²", "a² - b² = c"], correct: 1, explanation: "Im rechtwinkligen Dreieck gilt: a² + b² = c², wobei c die Hypotenuse (längste Seite, gegenüber dem rechten Winkel) ist.", kategorie: "Geometrie", schwierigkeit: "leicht" },
    { id: 4, question: "Was ist der Mittelwert (Durchschnitt) der Zahlen 4, 7, 9, 10?", options: ["7", "7.5", "8", "9"], correct: 1, explanation: "Mittelwert = Summe aller Werte ÷ Anzahl der Werte = (4 + 7 + 9 + 10) ÷ 4 = 30 ÷ 4 = 7.5", kategorie: "Statistik", schwierigkeit: "leicht" },
    { id: 5, question: "Was ist sin(30°)?", options: ["1", "0.5", "√2/2 ≈ 0.707", "√3/2 ≈ 0.866"], correct: 1, explanation: "sin(30°) = 1/2 = 0.5. Dies ist ein Standardwert der Trigonometrie. Merkhilfe: Im gleichseitigen Dreieck (alle Winkel 60°) halbiert die Höhe den Basiswinkel auf 30°.", kategorie: "Trigonometrie", schwierigkeit: "mittel" },
  ],

  biologie: [
    { id: 1, question: "Was ist die Hauptfunktion der Mitochondrien in der Zelle?", options: ["Proteinsynthese", "Energiegewinnung durch Zellatmung (ATP-Produktion)", "Speicherung von Erbinformation", "Transport von Stoffen"], correct: 1, explanation: "Mitochondrien sind die 'Kraftwerke der Zelle': Sie gewinnen durch oxidative Phosphorylierung (Zellatmung) Energie in Form von ATP aus Glukose und Sauerstoff.", kategorie: "Zellbiologie", schwierigkeit: "leicht" },
    { id: 2, question: "Was versteht man unter dem 'Zentralen Dogma der Molekularbiologie'?", options: ["DNA → RNA → Protein", "Protein → RNA → DNA", "RNA → DNA → Protein", "Protein → DNA → RNA"], correct: 0, explanation: "Das Zentrale Dogma beschreibt den Informationsfluss: DNA wird zu RNA transkribiert, RNA wird zu Protein translatiert. Dieser Fluss ist (fast) unidirektional.", kategorie: "Genetik", schwierigkeit: "mittel" },
    { id: 3, question: "Was ist der Unterschied zwischen Fotosynthese und Zellatmung?", options: ["Es gibt keinen Unterschied", "Fotosynthese baut Glukose auf (speichert Energie), Zellatmung baut Glukose ab (gewinnt Energie)", "Beide Prozesse laufen nur in Pflanzen ab", "Zellatmung findet nur nachts statt"], correct: 1, explanation: "Fotosynthese: CO₂ + H₂O + Licht → Glukose + O₂ (Energiespeicherung). Zellatmung: Glukose + O₂ → CO₂ + H₂O + ATP (Energiegewinnung). Sie sind quasi umgekehrte Prozesse.", kategorie: "Physiologie", schwierigkeit: "leicht" },
    { id: 4, question: "Was ist natürliche Selektion (Darwin)?", options: ["Alle Individuen einer Art sind gleich", "Individuen mit vorteilhaften Merkmalen überleben und pflanzen sich häufiger fort", "Mutationen entstehen absichtlich", "Stärkere Tiere fressen immer schwächere"], correct: 1, explanation: "Natürliche Selektion: In einer Population gibt es Variationen. Individuen mit Merkmalen, die besser an die Umwelt angepasst sind, überleben häufiger und geben ihre Gene weiter.", kategorie: "Evolution", schwierigkeit: "leicht" },
    { id: 5, question: "Was ist ein Ökosystem?", options: ["Nur die Gesamtheit aller Tiere in einem Gebiet", "Die Gesamtheit aller Lebewesen (Biozönose) und ihrer unbelebten Umwelt (Biotop) in einem Gebiet", "Nur die Pflanzen in einem Lebensraum", "Ein Labor zur Untersuchung von Organismen"], correct: 1, explanation: "Ein Ökosystem besteht aus der Biozönose (alle Lebewesen: Produzenten, Konsumenten, Destruenten) und dem Biotop (unbelebte Umwelt: Boden, Wasser, Klima).", kategorie: "Ökologie", schwierigkeit: "leicht" },
  ],

  chemie: [
    { id: 1, question: "Was ist der Unterschied zwischen einem Atom und einem Molekül?", options: ["Es gibt keinen Unterschied", "Ein Atom ist die kleinste Einheit eines Elements; ein Molekül besteht aus zwei oder mehr Atomen", "Ein Molekül ist kleiner als ein Atom", "Atome haben Ladung, Moleküle nicht"], correct: 1, explanation: "Ein Atom ist die kleinste Einheit eines chemischen Elements (z.B. ein Sauerstoffatom O). Ein Molekül entsteht durch die Verbindung von zwei oder mehr Atomen (z.B. O₂, H₂O).", kategorie: "Atombau", schwierigkeit: "leicht" },
    { id: 2, question: "Was beschreibt der pH-Wert einer Lösung?", options: ["Die Temperatur der Lösung", "Den Säuregehalt: pH < 7 = sauer, pH = 7 = neutral, pH > 7 = basisch", "Die Dichte der Lösung", "Die Konzentration von Salz in der Lösung"], correct: 1, explanation: "Der pH-Wert misst die Konzentration von H⁺-Ionen. pH < 7: sauer (z.B. Zitronensaft pH ≈ 2), pH = 7: neutral (Wasser), pH > 7: basisch/alkalisch (z.B. Natronlauge).", kategorie: "Säuren & Basen", schwierigkeit: "leicht" },
    { id: 3, question: "Was ist eine exotherme Reaktion?", options: ["Eine Reaktion, die Energie aufnimmt", "Eine Reaktion, die Energie (Wärme) abgibt", "Eine Reaktion, die bei tiefen Temperaturen stattfindet", "Eine Reaktion ohne Energieveränderung"], correct: 1, explanation: "Bei einer exothermen Reaktion wird Energie (meist als Wärme) an die Umgebung abgegeben. Die Produkte haben weniger Energie als die Ausgangsstoffe. Beispiel: Verbrennung.", kategorie: "Reaktionsgleichungen", schwierigkeit: "leicht" },
    { id: 4, question: "Was ist eine kovalente Bindung?", options: ["Eine Bindung zwischen Metall und Nichtmetall (Ionenbindung)", "Eine Bindung durch gemeinsame Elektronenpaare zwischen Nichtmetallen", "Eine Bindung durch frei bewegliche Elektronen in Metallen", "Eine Bindung durch elektrostatische Anziehung"], correct: 1, explanation: "Kovalente (oder Atombindung) entsteht, wenn zwei Nichtmetallatome Elektronenpaare teilen. Beispiele: H₂, H₂O, CO₂. Die Atome erreichen so eine stabile Edelgaskonfiguration.", kategorie: "Chemische Bindungen", schwierigkeit: "mittel" },
    { id: 5, question: "Was ist ein Isomer in der organischen Chemie?", options: ["Verbindungen mit gleicher Formel und gleicher Struktur", "Verbindungen mit gleicher Molekülformel, aber unterschiedlicher Strukturformel", "Verbindungen mit gleicher Masse, aber unterschiedlicher Formel", "Radioaktive Varianten eines Elements"], correct: 1, explanation: "Isomere haben dieselbe Molekülformel (gleiche Anzahl Atome), aber eine andere Anordnung der Atome. Beispiel: Butan und Isobutan (beide C₄H₁₀) sind Isomere.", kategorie: "Organische Chemie", schwierigkeit: "mittel" },
  ],

  physik: [
    { id: 1, question: "Was besagt das erste Newtonsche Gesetz (Trägheitsgesetz)?", options: ["Kraft = Masse × Beschleunigung", "Ein Körper bleibt in Ruhe oder gleichförmiger Bewegung, solange keine Kraft auf ihn wirkt", "Actio = Reactio", "Energie kann weder erzeugt noch vernichtet werden"], correct: 1, explanation: "Das Trägheitsgesetz: Ein Körper ändert seinen Bewegungszustand nur, wenn eine Kraft auf ihn wirkt. Ohne Kraft: Ruhe bleibt Ruhe, gleichförmige Bewegung bleibt gleichförmig.", kategorie: "Mechanik", schwierigkeit: "leicht" },
    { id: 2, question: "Was ist elektrischer Widerstand (R) und in welcher Einheit wird er gemessen?", options: ["Die Spannung, gemessen in Volt", "Das Verhältnis von Spannung zu Stromstärke (R = U/I), gemessen in Ohm (Ω)", "Die Energie, gemessen in Joule", "Die Leistung, gemessen in Watt"], correct: 1, explanation: "Elektrischer Widerstand R = U/I (Ohmsches Gesetz). Er beschreibt, wie stark ein Leiter den Stromfluss hemmt. Einheit: Ohm (Ω). Je grösser R, desto kleiner der Strom bei gleicher Spannung.", kategorie: "Elektrizität", schwierigkeit: "leicht" },
    { id: 3, question: "Was ist der Unterschied zwischen Reflexion und Brechung von Licht?", options: ["Es gibt keinen Unterschied", "Reflexion: Licht wird zurückgeworfen. Brechung: Licht ändert beim Übergang zwischen Medien seine Richtung.", "Brechung findet nur im Vakuum statt", "Reflexion verändert die Farbe des Lichts"], correct: 1, explanation: "Reflexion: Licht trifft auf eine Oberfläche und wird zurückgeworfen (Einfallswinkel = Ausfallswinkel). Brechung: Licht tritt in ein neues Medium ein und ändert dabei seine Richtung (Snelliussches Gesetz).", kategorie: "Optik", schwierigkeit: "leicht" },
    { id: 4, question: "Was beschreibt der erste Hauptsatz der Thermodynamik?", options: ["Wärme fliesst immer von kalt nach warm", "Energie kann weder erzeugt noch vernichtet werden – nur umgewandelt", "Alle Gase dehnen sich bei Erwärmung gleich aus", "Wärme ist eine Form von Materie"], correct: 1, explanation: "Der erste Hauptsatz der Thermodynamik ist der Energieerhaltungssatz: Die Gesamtenergie eines abgeschlossenen Systems bleibt konstant. Energie kann nur von einer Form in eine andere umgewandelt werden.", kategorie: "Thermodynamik", schwierigkeit: "mittel" },
    { id: 5, question: "Was ist die Frequenz einer Welle?", options: ["Die Höhe der Welle", "Die Anzahl der Schwingungen pro Sekunde, gemessen in Hertz (Hz)", "Die Geschwindigkeit der Welle", "Der Abstand zwischen zwei Wellenbergen"], correct: 1, explanation: "Frequenz f = Anzahl der Schwingungen pro Sekunde. Einheit: Hertz (Hz). Zusammenhang: f = 1/T (T = Schwingungsdauer). Hohe Frequenz = viele Schwingungen pro Sekunde.", kategorie: "Wellen", schwierigkeit: "leicht" },
  ],

  geschichte: [
    { id: 1, question: "Was war die Hauptursache des Ersten Weltkriegs (1914–1918)?", options: ["Nur das Attentat auf Franz Ferdinand", "Ein Zusammenspiel aus Nationalismus, Imperialismus, Bündnissystemen und dem Attentat von Sarajevo", "Wirtschaftliche Konkurrenz zwischen USA und Europa", "Religiöse Konflikte zwischen Christen und Muslimen"], correct: 1, explanation: "Der Erste Weltkrieg hatte viele Ursachen: Nationalismus, Imperialismus, das Wettrüsten, starre Bündnissysteme und die Julikrise 1914 (ausgelöst durch das Attentat auf Erzherzog Franz Ferdinand).", kategorie: "Ereignisse & Ursachen", schwierigkeit: "mittel" },
    { id: 2, question: "Was ist Quellenkritik in der Geschichtswissenschaft?", options: ["Das Abschreiben von Quellen", "Die kritische Prüfung einer Quelle auf Herkunft, Entstehungszeit, Absicht und Zuverlässigkeit", "Das Suchen nach neuen Quellen in Archiven", "Das Übersetzen historischer Texte"], correct: 1, explanation: "Quellenkritik umfasst: äussere Kritik (Wer? Wann? Wo?) und innere Kritik (Warum? Für wen? Wie zuverlässig?). Jede Quelle hat einen Standpunkt und muss kritisch hinterfragt werden.", kategorie: "Quellenkritik", schwierigkeit: "mittel" },
    { id: 3, question: "Was versteht man unter dem 'Kalten Krieg' (1947–1991)?", options: ["Ein Krieg mit sehr tiefen Temperaturen", "Die ideologische und politische Konfrontation zwischen USA (Westen) und UdSSR (Osten) ohne direkten Krieg", "Ein Wirtschaftskrieg zwischen Europa und Asien", "Ein Konflikt innerhalb der NATO"], correct: 1, explanation: "Der Kalte Krieg war die Systemkonfrontation zwischen dem westlichen Kapitalismus (USA) und dem östlichen Kommunismus (UdSSR). Trotz Rüstungswettlauf und Stellvertreterkriegen kam es nie zu einem direkten Krieg.", kategorie: "Epochen", schwierigkeit: "leicht" },
    { id: 4, question: "Was ist der Unterschied zwischen einer Primärquelle und einer Sekundärquelle?", options: ["Es gibt keinen Unterschied", "Primärquellen stammen aus der Zeit des Ereignisses; Sekundärquellen sind spätere Interpretationen", "Sekundärquellen sind zuverlässiger", "Primärquellen sind immer schriftlich"], correct: 1, explanation: "Primärquellen: Dokumente, Objekte oder Berichte aus der Zeit des Ereignisses (z.B. Tagebücher, Fotos, Verträge). Sekundärquellen: Spätere Interpretationen und Analysen (z.B. Geschichtsbücher).", kategorie: "Quellenkritik", schwierigkeit: "leicht" },
    { id: 5, question: "Was war die Bedeutung der Französischen Revolution (1789)?", options: ["Sie hatte keine Auswirkungen ausserhalb Frankreichs", "Sie verbreitete die Ideen von Freiheit, Gleichheit und Volkssouveränität und beeinflusste Europa nachhaltig", "Sie führte sofort zur Demokratie in ganz Europa", "Sie war hauptsächlich ein wirtschaftlicher Konflikt"], correct: 1, explanation: "Die Französische Revolution verbreitete die Ideen der Aufklärung (Liberté, Égalité, Fraternité), beendete den Absolutismus in Frankreich und beeinflusste politische Bewegungen in ganz Europa.", kategorie: "Epochen", schwierigkeit: "mittel" },
  ],

  geografie: [
    { id: 1, question: "Was ist der Unterschied zwischen Klima und Wetter?", options: ["Es gibt keinen Unterschied", "Wetter ist der kurzfristige Zustand der Atmosphäre; Klima ist der langfristige Durchschnitt über mindestens 30 Jahre", "Klima ist lokaler als Wetter", "Wetter beschreibt globale Muster, Klima lokale"], correct: 1, explanation: "Wetter: aktueller, kurzfristiger Zustand der Atmosphäre (heute regnerisch). Klima: Langzeitdurchschnitt meteorologischer Grössen über mindestens 30 Jahre (z.B. Klimazone Mitteleuropa).", kategorie: "Klimazonen", schwierigkeit: "leicht" },
    { id: 2, question: "Was ist der demographische Übergang?", options: ["Die Wanderung von Menschen in Städte", "Das Modell, das den Übergang von hoher zu niedriger Geburten- und Sterberate beschreibt", "Die Alterung der Bevölkerung in Industrieländern", "Die Zunahme der Weltbevölkerung durch Einwanderung"], correct: 1, explanation: "Das Modell des demographischen Übergangs beschreibt, wie Länder von hoher Geburten- und Sterberate (Entwicklungsländer) zu niedriger Geburten- und Sterberate (Industrieländer) übergehen.", kategorie: "Humangeografie", schwierigkeit: "mittel" },
    { id: 3, question: "Was sind Plattentektonik und ihre Folgen?", options: ["Die Bewegung von Meeresströmungen", "Die Bewegung der Erdkrustenplatten, die Erdbeben, Vulkanismus und Gebirgsbildung verursacht", "Die Entstehung von Wüsten durch Wind", "Die Veränderung von Küstenlinien durch Meeresströmungen"], correct: 1, explanation: "Die Erdkruste besteht aus Platten, die sich bewegen. An Plattengrenzen entstehen: Erdbeben (Transformgrenzen), Vulkane (divergente/konvergente Grenzen) und Gebirge (Kollisionsgrenzen).", kategorie: "Physische Geografie", schwierigkeit: "leicht" },
    { id: 4, question: "Was ist Globalisierung in der Wirtschaftsgeografie?", options: ["Die Ausbreitung einer Sprache weltweit", "Die zunehmende weltweite Vernetzung von Wirtschaft, Gesellschaft und Kultur", "Die Entstehung von Megacities", "Der Rückgang des Welthandels"], correct: 1, explanation: "Globalisierung bezeichnet die zunehmende internationale Verflechtung in Wirtschaft (Welthandel, multinationale Konzerne), Gesellschaft (Migration) und Kultur (Medien, Sprache).", kategorie: "Wirtschaftsgeografie", schwierigkeit: "leicht" },
    { id: 5, question: "Was zeigt ein Klimadiagramm?", options: ["Nur die Temperaturkurve eines Ortes", "Den monatlichen Verlauf von Temperatur (Kurve) und Niederschlag (Balken) an einem Ort", "Die Bevölkerungsdichte einer Region", "Die Höhenverteilung eines Gebiets"], correct: 1, explanation: "Ein Klimadiagramm (Walter-Lieth-Diagramm) zeigt für jeden Monat: Durchschnittstemperatur (Kurve, linke Achse) und Niederschlag (Balken, rechte Achse). Es ermöglicht die Bestimmung der Klimazone.", kategorie: "Kartenkunde", schwierigkeit: "leicht" },
  ],

  psychpaed: [
    { id: 1, question: "Was unterscheidet klassische von operanter Konditionierung?", options: ["Es gibt keinen Unterschied", "Klassisch: Reflexe werden an neue Reize geknüpft (Pawlow). Operant: Verhalten wird durch Konsequenzen verstärkt oder bestraft (Skinner)", "Operante Konditionierung funktioniert nur bei Tieren", "Klassische Konditionierung ist moderner"], correct: 1, explanation: "Klassische Konditionierung (Pawlow): Ein neutraler Reiz wird mit einem Reflex verknüpft. Operante Konditionierung (Skinner): Verhalten wird durch positive/negative Konsequenzen geformt.", kategorie: "Lerntheorien", schwierigkeit: "mittel" },
    { id: 2, question: "Was ist die 'Zone der nächsten Entwicklung' nach Wygotski?", options: ["Der aktuelle Entwicklungsstand eines Kindes", "Der Bereich zwischen dem, was ein Kind alleine kann, und dem, was es mit Unterstützung erreichen kann", "Die maximale Intelligenz eines Kindes", "Der Altersbereich von 0–3 Jahren"], correct: 1, explanation: "Wygotski: Die Zone der nächsten Entwicklung (ZNE) ist der Bereich zwischen dem aktuellen Entwicklungsstand (alleine lösbar) und dem potenziellen Stand (mit Hilfe lösbar). Guter Unterricht operiert in dieser Zone.", kategorie: "Entwicklungspsychologie", schwierigkeit: "mittel" },
    { id: 3, question: "Was versteht man unter 'intrinsischer Motivation' im Lernkontext?", options: ["Motivation durch äussere Belohnungen (Noten, Lob)", "Motivation, die aus dem eigenen Interesse und der Freude an der Sache entsteht", "Motivation durch Angst vor Strafe", "Motivation durch Konkurrenz mit anderen"], correct: 1, explanation: "Intrinsische Motivation entsteht aus dem eigenen Interesse, der Neugier oder dem Erleben von Kompetenz. Sie ist nachhaltiger als extrinsische Motivation (Belohnungen, Noten).", kategorie: "Motivation", schwierigkeit: "leicht" },
    { id: 4, question: "Was ist das Konzept der 'Scaffolding' im Unterricht?", options: ["Das Bauen von Schulgebäuden", "Temporäre Unterstützungsstrategien, die schrittweise zurückgezogen werden, wenn Lernende selbständiger werden", "Das Erstellen von Lernplänen", "Die Beurteilung von Schülerleistungen"], correct: 1, explanation: "Scaffolding (Gerüst): Die Lehrperson bietet anfangs viel Unterstützung (Erklärungen, Strukturen, Beispiele) und zieht diese schrittweise zurück, wenn die Lernenden kompetenter werden.", kategorie: "Unterrichtsmethoden", schwierigkeit: "mittel" },
    { id: 5, question: "Was ist 'kognitive Dissonanz' nach Festinger?", options: ["Ein Zustand der Entspannung", "Das unangenehme Gefühl, das entsteht, wenn Überzeugungen und Verhalten im Widerspruch stehen", "Die Unfähigkeit, sich zu konzentrieren", "Ein Lernproblem bei Kindern"], correct: 1, explanation: "Kognitive Dissonanz (Festinger): Wenn Überzeugungen, Einstellungen oder Verhalten nicht übereinstimmen, entsteht ein unangenehmes Spannungsgefühl. Menschen versuchen, diesen Widerspruch aufzulösen.", kategorie: "Sozialpsychologie", schwierigkeit: "mittel" },
  ],

  philosophie: [
    { id: 1, question: "Was ist der Unterschied zwischen Deduktion und Induktion?", options: ["Es gibt keinen Unterschied", "Deduktion: vom Allgemeinen zum Besonderen. Induktion: vom Besonderen zum Allgemeinen", "Induktion ist sicherer als Deduktion", "Deduktion basiert auf Beobachtungen"], correct: 1, explanation: "Deduktion: Aus allgemeinen Prämissen wird eine notwendige Schlussfolgerung gezogen (z.B. Syllogismus). Induktion: Aus vielen Einzelbeobachtungen wird eine allgemeine Regel abgeleitet (nie 100% sicher).", kategorie: "Logik", schwierigkeit: "mittel" },
    { id: 2, question: "Was ist der 'kategorische Imperativ' nach Kant?", options: ["Ein Gesetz des Staates", "Das moralische Grundprinzip: Handle nur nach der Maxime, die du als allgemeines Gesetz wollen könntest", "Ein Gebot der Kirche", "Eine Regel für wissenschaftliches Arbeiten"], correct: 1, explanation: "Kants kategorischer Imperativ (Grundformel): 'Handle nur nach derjenigen Maxime, durch die du zugleich wollen kannst, dass sie ein allgemeines Gesetz werde.' Er ist die Grundlage der deontologischen Ethik.", kategorie: "Ethik", schwierigkeit: "mittel" },
    { id: 3, question: "Was ist der Unterschied zwischen Empirismus und Rationalismus?", options: ["Es gibt keinen Unterschied", "Empirismus: Wissen kommt aus Erfahrung (Locke, Hume). Rationalismus: Wissen kommt aus der Vernunft (Descartes, Leibniz)", "Rationalismus ist moderner", "Empirismus ist eine Naturwissenschaft"], correct: 1, explanation: "Empirismus (Locke, Hume): Alle Erkenntnis stammt aus Sinneserfahrung. Rationalismus (Descartes, Leibniz): Wahres Wissen kommt aus der reinen Vernunft, unabhängig von Erfahrung.", kategorie: "Erkenntnistheorie", schwierigkeit: "mittel" },
    { id: 4, question: "Was ist 'Utilitarismus' als ethische Theorie?", options: ["Die Ansicht, dass nur Pflichten zählen", "Die Ansicht, dass eine Handlung gut ist, wenn sie den grössten Nutzen für die grösste Zahl von Menschen bringt", "Die Ansicht, dass Moral relativ ist", "Die Ansicht, dass Tugend das höchste Gut ist"], correct: 1, explanation: "Utilitarismus (Bentham, Mill): Eine Handlung ist moralisch richtig, wenn sie den Gesamtnutzen (Glück, Wohlbefinden) maximiert. Konsequenzethik: Die Folgen der Handlung sind entscheidend.", kategorie: "Ethik", schwierigkeit: "mittel" },
    { id: 5, question: "Was ist Platons 'Höhlengleichnis'?", options: ["Eine Geschichte über Bergsteiger", "Ein Gleichnis über den Unterschied zwischen Scheinwelt (Sinneswahrnehmung) und wahrer Erkenntnis (Ideen)", "Eine Metapher für das Gefängnissystem", "Ein Beispiel für politische Unterdrückung"], correct: 1, explanation: "Im Höhlengleichnis sitzen Menschen in einer Höhle und sehen nur Schatten an der Wand (= Sinneswahrnehmung). Wer die Höhle verlässt, erkennt die wahre Welt (= Ideenwelt). Platon illustriert damit den Weg zur Erkenntnis.", kategorie: "Metaphysik", schwierigkeit: "leicht" },
  ],

  medienkommunikation: [
    { id: 1, question: "Was beschreibt das Kommunikationsmodell von Shannon und Weaver?", options: ["Ein Modell für soziale Netzwerke", "Ein technisches Modell: Sender → Kanal → Empfänger, mit möglichen Störquellen", "Ein Modell für nonverbale Kommunikation", "Ein Modell für Massenkommunikation"], correct: 1, explanation: "Shannon-Weaver (1949): Sender codiert Botschaft → Kanal (mit Rauschen/Störungen) → Empfänger decodiert. Ursprünglich für technische Kommunikation, aber auf menschliche Kommunikation übertragen.", kategorie: "Kommunikationsmodelle", schwierigkeit: "leicht" },
    { id: 2, question: "Was sind die 'vier Seiten einer Nachricht' nach Schulz von Thun?", options: ["Sender, Empfänger, Kanal, Rückmeldung", "Sachinhalt, Selbstoffenbarung, Beziehung, Appell", "Inhalt, Form, Kontext, Wirkung", "Verbal, nonverbal, paraverbal, schriftlich"], correct: 1, explanation: "Schulz von Thun: Jede Nachricht hat vier Ebenen: Sachinhalt (Was ist die Information?), Selbstoffenbarung (Was sage ich über mich?), Beziehung (Was halte ich vom Empfänger?), Appell (Was will ich erreichen?).", kategorie: "Kommunikationsmodelle", schwierigkeit: "mittel" },
    { id: 3, question: "Was ist 'Agenda Setting' in der Medienwirkungsforschung?", options: ["Die Fähigkeit von Medien, Meinungen direkt zu verändern", "Die Fähigkeit von Medien, zu beeinflussen, welche Themen als wichtig wahrgenommen werden", "Die Planung von Medienprogrammen", "Die Zensur von Medieninhalten"], correct: 1, explanation: "Agenda Setting (McCombs & Shaw): Medien bestimmen nicht, was wir denken, aber worüber wir nachdenken. Themen, die viel Medienaufmerksamkeit erhalten, werden von der Öffentlichkeit als wichtiger wahrgenommen.", kategorie: "Medienwirkung", schwierigkeit: "mittel" },
    { id: 4, question: "Was ist der Unterschied zwischen linearen und nicht-linearen Medien?", options: ["Es gibt keinen Unterschied", "Lineare Medien: fester Zeitablauf (TV, Radio). Nicht-lineare Medien: Nutzer bestimmt Reihenfolge und Zeit (Internet, Streaming)", "Nicht-lineare Medien sind älter", "Lineare Medien sind interaktiver"], correct: 1, explanation: "Lineare Medien (TV, Radio, Zeitung): Inhalte werden in fester Reihenfolge konsumiert. Nicht-lineare Medien (Internet, Streaming, Social Media): Nutzer wählen Inhalte, Zeit und Reihenfolge selbst.", kategorie: "Digitale Medien", schwierigkeit: "leicht" },
    { id: 5, question: "Was ist 'Framing' in der Medienkommunikation?", options: ["Das Einrahmen von Bildern", "Die Art, wie Medien Themen durch Auswahl und Betonung bestimmter Aspekte darstellen und interpretieren", "Die technische Übertragung von Signalen", "Das Erstellen von Nachrichtenartikeln"], correct: 1, explanation: "Framing: Medien wählen aus, welche Aspekte eines Themas betont werden (z.B. Migration als 'Bedrohung' vs. 'Bereicherung'). Der Rahmen (Frame) beeinflusst, wie Rezipienten ein Thema wahrnehmen.", kategorie: "Medienanalyse", schwierigkeit: "mittel" },
  ],
};
